### ISSUE TITLE
Can't modify records of unicode/punicoded domains

### ISSUE THREAD

**Issue by csmith** [mydnshost/mydnshost-api#124]
e.g. trying to update münchen.com

> There was some errors with some of the submitted records. None of the changes have been saved. Please fix the problems and then try again.

> checkzone failure:
zone xn--mnchen-3ya.com/IN: loading from master file /tmp/chk-mnchen.com-DeW8SX failed: file not found

**Comment by ShaneMcC** [comment]
Fixed in 88d5dade9c8cb9ea175f32d97d1877456375c237
