### ISSUE TITLE
Can remove users with higher roles in shared domain

### ISSUE THREAD

**Issue by csmith** [mydnshost/mydnshost-api#26]
The permission check when modifying users in a shared domain is incorrect - it allows you to modify any user as long as the new role is strictly less than your role.

So if userA has admin, userB has read, userB can change userA's role to "none" as it's lower than "read"!

**Comment by ShaneMcC** [comment]
Thankfully it's not quite that severe - only owners or admins can change access - but still, admins shouldn't be able to demote other admins or owners.

**Comment by csmith** [comment]
![image](https://user-images.githubusercontent.com/189133/33364421-44d73b04-d4dc-11e7-9346-ed8e2a5c848a.png)
