### ISSUE TITLE
E-mail subject lines get HTML encoded

### ISSUE THREAD

**Issue by csmith** [mydnshost/mydnshost-api#27]
Adding an API key with an apostrophe in results in an email with:

`Subject: New API Key Updated: abcd&#039;efgh`

The subject's obviously not HTML, so it just ends up displaying the entity to the user

**Comment by ShaneMcC** [comment]
This was more annoying to debug than it should have been!

Changing the autoescape option for twig only changes newly-generated templates, so existing cached stuff is unaffected. Lame, otherwise I'd have just changed the default escaping strategy to `false` rather than leaving it as 'html'
