### ISSUE TITLE
Mask API keys in email

### ISSUE THREAD

**Issue by csmith** [mydnshost/mydnshost-api#48]
To view an API key you have to login to mydnshost, enter a second factor, re-enter your password on the profile page, then click to reveal it. It's nice and very resistant to anyone shoulder-surfing the key, or using a logged-in session to steal them.

On the other hand the keys are sent out in plain text emails. That seems problematic:

- It's possible some email providers still don't use TLS so it may be going in plain text for some of the journey
- Anyone seeing the screen (or seeing a long enough notification popup in a stream/meeting/etc) can see the key
- Anyone who gains access to any device where the email account is logged into (which for most people is going to be all their devices) can get at the key

Would be nice if the keys were masked in the email and the only way to view them was to log into the website.

**Comment by ShaneMcC** [comment]
Masked keys look something like: `E157CD83-****-****-****-*******092A7`
