### ISSUE TITLE
Support for putting domains into folders

### ISSUE THREAD

**Issue by csmith** [mydnshost/mydnshost-api#56]
For domain hoarders it'd be nice if you could group domains into folders

I think single level would be OK to start with, but nested folders eventually might be nice (e.g. work/client/foobar, work/client/baz, personal/stuff, ...)

I can't decide if you'd want to force all domains into a "root" folder or allow domains to not be in a folder?

I'd also expect the API to list the domains flatly as well (would be annoying having to iterate over each folder for most applications that want to poke the API), so I'm not sure how you'd expose it.

Maybe labels would be easier (and having the frontend automagically group things with the same labels in collapsible sections)?

**Comment by ShaneMcC** [comment]
Initial thoughts:

A `{userid, domainid} => foldername` mapping. Per-user, returned in the API calls as an extra field on the domain and let the front-end display it however it wants. Nesting achieved by splitting on `/` (Kinda like how gmail does nested-labels)


Doesn't really work for #57 but that can be handled separately I think

**Comment by ShaneMcC** [comment]
https://github.com/mydnshost/mydnshost-frontend/commit/4e393346a0eb18547707999ae7e31a7002d488cc
